<a href="<?php echo $this->url(array(), 'home'); ?>">Home</a>
<h2>Sitemap</h2>
<?php if (count($this->sites)): ?>
<table>
    <tr>
        <td>ID</td>    
        <td>Titel</td>    
        <td>Lang</td>    
        <td>Keywords</td>    
        <td>Description</td>    
        <td>Robots</td>    
        <td>Directory</td>    
        <td>Name</td>    
        <td>Type</td>    
        <td>Path</td>    
        <td>Landpage</td>    
        <td>Onlymember</td>    
        <td>OnlyPayed</td>    
    </tr>
    <?php foreach ($this->sites as $site):?>
        <tr>
            <td><?php echo $this->escape($site->id); ?></td>
            <td><?php echo $this->escape($site->title); ?></td>
            <td><?php echo $this->escape($site->language); ?></td>
            <td><?php echo $this->escape($site->keyword); ?></td>
            <td><?php echo $this->escape($site->descr); ?></td>
            <td><?php echo $this->escape($site->robots); ?></td>
            <td><?php echo $this->escape($site->directory); ?></td>
            <td><?php echo $this->escape($site->name); ?></td>
            <td><?php echo $this->escape($site->type); ?></td>
            <td><?php echo $this->escape($site->path); ?></td>
            <td><?php echo $this->escape($site->landingpage); ?></td>
            <td><?php echo $this->escape($site->onlymember); ?></td>
            <td><?php echo $this->escape($site->onlypayed); ?></td>    
        </tr>  
    <?php endforeach; ?>
</table>

<?php else: ?>
No records found - hab nüscht gefunden!!
<?php endif; ?>


